services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    networks:
      - vaultwarden
    environment:
      DOMAIN: ${VAULTWARDEN_DOMAIN}
      SIGNUPS_ALLOWED: ${VAULTWARDEN_SIGNUPS_ALLOWED}
      ADMIN_TOKEN: ${VAULTWARDEN_ADMIN_TOKEN}
      ICONS_SERVICE: internal
    volumes:
      - ./vw-data/:/data/
    ports:
      - "8888:80"

networks:
  vaultwarden:
    driver: bridge
